---
learner_name: maddpg
learning_rate: 0.01
discount_factor: 0.95
polyak: 0.99
batch_size: 1024
buffer_size: 1000000
update_interval: 100
hidden_units: 64
local_q: False
actor_bnorm: True
weight_init: True
critic_bnorm: True
